# Generated by Django 5.1.4 on 2025-01-18 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listindividual',
            name='list_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listcategory',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner_archiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listcategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listindividual',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_owner_archiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listindividual',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_category', to='lists.listcategory'),
        ),
        migrations.AlterField(
            model_name='listindividual',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_owner_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listindividual',
            name='list_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listindividual',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_owner_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
