# Generated by Django 5.1.5 on 2025-02-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_item_cost_alter_listcategory_category_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcategory',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
